<template>
  <v-btn
    color="primary"
    :loading="isGeneratingPDF"
    @click="generatePDF"
    class="action-btn"
    rounded
  >
    <span class="button-text">Download Safety Report</span>
    <v-progress-circular
      v-if="isGeneratingPDF"
      indeterminate
      size="20"
      width="2"
      color="white"
      class="ml-2"
    ></v-progress-circular>
  </v-btn>
</template>

<script>
import html2pdf from 'html2pdf.js'

export default {
  name: 'ChecklistPDF',
  props: {
    checklistData: {
      type: Object,
      required: true,
      default: () => ({
        overallSafetyScore: 0,
        overallSafetyLevel: 'medium',
        overallSafetyMessage: '',
        categoryResults: [],
        improvementRecommendations: [],
        safetyStrengths: []
      })
    }
  },
  data() {
    return {
      isGeneratingPDF: false
    }
  },
  methods: {
    formatCategoryName(name) {
      return name.split('_')
        .map(word => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
        .join(' ')
    },
    async generatePDF() {
      this.isGeneratingPDF = true
      try {
        const element = document.createElement('div')
        const options = {
          margin: [10, 10],
          filename: 'ShieldSkills_Security_Report.pdf',
          image: { type: 'jpeg', quality: 0.98 },
          html2canvas: { 
            scale: 2,
            useCORS: true,
            logging: false,
            letterRendering: true
          },
          jsPDF: { 
            unit: 'mm',
            format: 'a4',
            orientation: 'portrait'
          }
        }
        
        element.innerHTML = `
          <div style="
            padding: 40px; 
            font-family: 'Helvetica', 'Arial', sans-serif; 
            max-width: 800px; 
            margin: 0 auto;
            background: linear-gradient(135deg, #FAFAFA 0%, #F5F5F5 100%);
            border-radius: 20px;
            box-shadow: 0 4px 20px rgba(0, 0, 0, 0.1);
          ">
            <!-- Header with Logo -->
            <div style="
              text-align: center; 
              margin-bottom: 40px;
              padding: 20px;
              background: white;
              border-radius: 15px;
              box-shadow: 0 2px 10px rgba(0, 0, 0, 0.05);
            ">
              <h1 style="
                color: #1a237e; 
                font-size: 32px; 
                margin-bottom: 15px;
                font-weight: 800;
              ">Online Safety Assessment Report</h1>
              <p style="
                color: #666; 
                font-size: 18px;
                font-weight: 500;
              ">Generated by ShieldSkills™ Security Platform</p>
            </div>
            
            <!-- Overall Score -->
            <div style="
              background: ${this.checklistData.overallSafetyLevel === 'high' 
                ? 'linear-gradient(135deg, #F0FDF4 0%, #DCFCE7 100%)'
                : this.checklistData.overallSafetyLevel === 'medium'
                ? 'linear-gradient(135deg, #FFF7ED 0%, #FFEDD5 100%)'
                : 'linear-gradient(135deg, #FEF2F2 0%, #FEE2E2 100%)'};
              padding: 30px;
              border-radius: 15px;
              margin-bottom: 40px;
              position: relative;
            ">
              <div style="display: flex; align-items: center;">
                <div style="
                  width: 48px;
                  height: 48px;
                  border-radius: 50%;
                  background: rgba(255, 255, 255, 0.9);
                  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);
                  margin-right: 20px;
                  display: flex;
                  align-items: center;
                  justify-content: center;
                ">
                  <img src="${this.checklistData.overallSafetyLevel === 'high' 
                    ? 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNCAyNCI+PHBhdGggZD0iTTEyIDEySDRhOCA4IDAgMCAwIDggOHYtOHptMC0yVjJhOCA4IDAgMCAwLTggOGg4em0yIDB2OGE4IDggMCAwIDAgOC04aC04em0wLTJoOGE4IDggMCAwIDAtOC04djh6IiBmaWxsPSIjMjJDNTVFIi8+PC9zdmc+'
                    : this.checklistData.overallSafetyLevel === 'medium'
                    ? 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNCAyNCI+PHBhdGggZD0iTTEyIDEySDRhOCA4IDAgMCAwIDggOHYtOHptMC0yVjJhOCA4IDAgMCAwLTggOGg4em0yIDB2OGE4IDggMCAwIDAgOC04aC04em0wLTJoOGE4IDggMCAwIDAtOC04djh6IiBmaWxsPSIjRjU5RTBCIi8+PC9zdmc+'
                    : 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNCAyNCI+PHBhdGggZD0iTTEyIDEySDRhOCA4IDAgMCAwIDggOHYtOHptMC0yVjJhOCA4IDAgMCAwLTggOGg4em0yIDB2OGE4IDggMCAwIDAgOC04aC04em0wLTJoOGE4IDggMCAwIDAtOC04djh6IiBmaWxsPSIjRUY0NDQ0Ii8+PC9zdmc+'
                  }" width="24" height="24" />
                </div>
                <div style="flex: 1;">
                  <h2 style="color: ${
                    this.checklistData.overallSafetyLevel === 'high' ? '#15803D'
                    : this.checklistData.overallSafetyLevel === 'medium' ? '#B45309'
                    : '#B91C1C'
                  }; font-size: 24px; margin: 0 0 10px 0;">
                    Your Online Safety Score: ${this.checklistData.overallSafetyScore}%
                  </h2>
                  <p style="color: #4B5563; font-size: 16px; margin: 0;">${this.checklistData.overallSafetyMessage}</p>
                  <div style="margin-top: 15px; background: rgba(255, 255, 255, 0.5); border-radius: 4px; height: 8px; overflow: hidden;">
                    <div style="width: ${this.checklistData.overallSafetyScore}%; height: 100%; background: ${
                      this.checklistData.overallSafetyLevel === 'high' ? '#15803D'
                      : this.checklistData.overallSafetyLevel === 'medium' ? '#B45309'
                      : '#B91C1C'
                    };"></div>
                  </div>
                </div>
              </div>
            </div>
            
            <!-- Category Scores -->
            <div style="margin-bottom: 40px;">
              <h2 style="color: #1E293B; font-size: 24px; margin-bottom: 20px;">Category Breakdown</h2>
              ${this.checklistData.categoryResults.map(category => `
                <div style="background: white; padding: 25px; border-radius: 12px; margin-bottom: 20px; box-shadow: 0 2px 8px rgba(0,0,0,0.1);">
                  <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 15px;">
                    <h3 style="color: #1E293B; font-size: 18px; margin: 0;">${this.formatCategoryName(category.name)}</h3>
                    <span style="
                      background: ${category.score >= 80 ? 'linear-gradient(135deg, #F0FDF4 0%, #DCFCE7 100%)'
                        : category.score >= 60 ? 'linear-gradient(135deg, #FFF7ED 0%, #FFEDD5 100%)'
                        : 'linear-gradient(135deg, #FEF2F2 0%, #FEE2E2 100%)'};
                      color: ${category.score >= 80 ? '#15803D'
                        : category.score >= 60 ? '#B45309'
                        : '#B91C1C'};
                      padding: 8px 15px;
                      border-radius: 20px;
                      font-weight: bold;">
                      ${category.score}%
                    </span>
                  </div>
                  <p style="color: #4B5563; font-size: 14px; margin: 0 0 15px 0; line-height: 1.5;">${category.message}</p>
                  <div style="background: #F1F5F9; border-radius: 4px; height: 6px; overflow: hidden;">
                    <div style="width: ${category.score}%; height: 100%; background: ${
                      category.score >= 80 ? '#15803D'
                      : category.score >= 60 ? '#B45309'
                      : '#B91C1C'
                    };"></div>
                  </div>
                </div>
              `).join('')}
            </div>
            
            <!-- Improvement Recommendations -->
            <div style="margin-bottom: 40px;">
              <h2 style="color: #1E293B; font-size: 24px; margin-bottom: 20px;">Recommended Improvements</h2>
              ${this.checklistData.improvementRecommendations.map(category => `
                <div style="margin-bottom: 30px;">
                  <h3 style="color: #1E293B; font-size: 20px; margin-bottom: 15px;">${this.formatCategoryName(category.name)}</h3>
                  ${category.items.map(item => `
                    <div style="background: white; padding: 20px; border-radius: 12px; margin-bottom: 15px; box-shadow: 0 2px 8px rgba(0,0,0,0.1);">
                      <div style="display: flex; align-items: center; margin-bottom: 10px;">
                        <span style="
                          background: ${item.priority === 'high' 
                            ? 'linear-gradient(135deg, #FEF2F2 0%, #FEE2E2 100%)'
                            : item.priority === 'medium'
                            ? 'linear-gradient(135deg, #FFF7ED 0%, #FFEDD5 100%)'
                            : 'linear-gradient(135deg, #F0F9FF 0%, #E0F2FE 100%)'};
                          color: ${item.priority === 'high' ? '#B91C1C'
                            : item.priority === 'medium' ? '#B45309'
                            : '#0C4A6E'};
                          padding: 5px 12px;
                          border-radius: 15px;
                          font-size: 12px;
                          font-weight: bold;">
                          ${item.priority === 'high' ? 'Critical' : item.priority === 'medium' ? 'Important' : 'Helpful'}
                        </span>
                      </div>
                      <h4 style="color: #1E293B; font-size: 16px; margin: 0 0 8px 0;">${item.title}</h4>
                      <p style="color: #4B5563; font-size: 14px; margin: 0; line-height: 1.5;">${item.description}</p>
                    </div>
                  `).join('')}
                </div>
              `).join('')}
            </div>
            
            <!-- Safety Strengths -->
            <div style="margin-bottom: 40px;">
              <h2 style="color: #1E293B; font-size: 24px; margin-bottom: 20px;">Your Security Strengths</h2>
              ${this.checklistData.safetyStrengths.map(strength => `
                <div style="background: #F0FDF4; padding: 20px; border-radius: 12px; margin-bottom: 15px;">
                  <div style="display: flex; align-items: flex-start;">
                    <div style="margin-right: 15px;">
                      <img src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNCAyNCI+PHBhdGggZD0iTTkgMTYuMTdMNC44MyAxMmwtMS40MiAxLjQxTDkgMTkgMjEgN2wtMS40MS0xLjQxeiIgZmlsbD0iIzE1ODAzRCIvPjwvc3ZnPg==" width="24" height="24" />
                    </div>
                    <div>
                      <h4 style="color: #15803D; font-size: 16px; margin: 0 0 8px 0;">${strength.title}</h4>
                      <p style="color: #4B5563; font-size: 14px; margin: 0; line-height: 1.5;">${strength.description}</p>
                    </div>
                  </div>
                </div>
              `).join('')}
            </div>
            
            <!-- Footer -->
            <div style="text-align: center; margin-top: 50px; padding-top: 20px; border-top: 2px solid #E3F2FD;">
              <p style="color: #4B5563; font-size: 14px;">Report generated on ${new Date().toLocaleDateString('en-US', { 
                year: 'numeric', 
                month: 'long', 
                day: 'numeric',
                hour: '2-digit',
                minute: '2-digit'
              })}</p>
              <p style="color: #1565C0; font-size: 16px; font-weight: bold;">ShieldSkills™ Security Assessment Report</p>
            </div>
          </div>
        `
        
        await html2pdf().set(options).from(element).save()
        this.$emit('pdf-generated', true)
      } catch (error) {
        console.error('Error generating PDF:', error)
        this.$emit('pdf-generated', false)
      } finally {
        this.isGeneratingPDF = false
      }
    }
  }
}
</script>

<style scoped>
.action-btn {
  min-width: 200px;
}

.button-text {
  white-space: nowrap;
}

@media (max-width: 600px) {
  .action-btn {
    min-width: 180px;
    height: 44px;
    font-size: 14px;
  }
}
</style> 